CREATE TABLE IF NOT EXISTS `RECETTES` (
											  `ID_RECETTE`  SMALLINT UNSIGNED AUTO_INCREMENT,
											  `NOM_RECETTE` VARCHAR(50) NOT NULL,
	                                                                                  `DATE_PUBLICATION_RECETTE` DATE        NOT NULL,
											  PRIMARY KEY (`ID_TYPE_INGREDIENT`),
											  UNIQUE KEY (`NOM_TYPE_INGREDIENT`)) ENGINE = InnoDB
																				  DEFAULT CHARSET = `UTF8`;

CREATE TABLE IF NOT EXISTS `CATEGORIES` (
										   `ID_CATEGORIE`  SMALLINT UNSIGNED AUTO_INCREMENT,
										   `NOM_CATEGORIE` VARCHAR(50) NOT NULL,
										   PRIMARY KEY (`ID_CATEGORIE`),
										   UNIQUE KEY (`NOM_CATEGORIE`)) ENGINE = InnoDB
																			 DEFAULT CHARSET = `UTF8`;
CREATE TABLE IF NOT EXISTS `INGREDIENTS` (
										   `ID_INGREDIENT`  SMALLINT UNSIGNED AUTO_INCREMENT,
										   `NOM_INGREDIENT` VARCHAR(50) NOT NULL,
										   PRIMARY KEY (`ID_INGREDIENT`),
										   UNIQUE KEY (`NOM_INGREDIENT`)) ENGINE = InnoDB
																			 DEFAULT CHARSET = `UTF8`;   
CREATE TABLE IF NOT EXISTS `INTERNAUTES` (
										   `ID_INTERNAUTE`  SMALLINT UNSIGNED AUTO_INCREMENT,
										   `NOM_INTERNAUTE` VARCHAR(50) NOT NULL,
										   `PRENOM_INTERNAUTE` VARCHAR(50) NOT NULL,
										   `AGE_INTERNAUTE` INT NOT NULL,
										   `MAIL_INTERNAUTE` VARCHAR(50) NOT NULL,
										   `MDP_INTERNAUTE` VARCHAR(50) NOT NULL,
										   `PSEUDO_INTERNAUTE` VARCHAR(50) NOT NULL,
										   PRIMARY KEY (`ID_INTERNAUTE`),
										   UNIQUE KEY (`MAIL_INTERNAUTE`, `PSEUDO_INTERNAUTE`)) ENGINE = InnoDB
																			 DEFAULT CHARSET = `UTF8`;   
